version: '2.1'
services:
  verdaccio:
    build: .
    container_name: verdaccio-docker-badges
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
volumes:
  verdaccio:
    driver: local
